version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SANDBOX_MODE: 'True'
    depends_on:
      - couchdb
    volumes:
      - ".:/app"
    ports:
      - "8000:80"
    command: sleep infinity
  # test:
  #   build:
  #     context: .
  #     dockerfile: DockerfileTest
  #   depends_on:
  #     - couchdb
  #   volumes:
  #     - "./src/openprocurement:/app/src/openprocurement:delegated"
  #     - "./docs:/app/docs:delegated"
  couchdb:
    image: "couchdb:1.6"
    volumes:
      - "./data:/var/lib/couchdb:delegated"
    environment:
      COUCHDB_USER: op
      COUCHDB_PASSWORD: op
    ports:
      - "5984:5984"